<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="68" started-at="2018-04-26T23:22:55Z" finished-at="2018-04-26T23:22:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="68" started-at="2018-04-26T23:22:55Z" finished-at="2018-04-26T23:22:55Z">
      <class name="testclasses.TestNG_ITestResultDemo">
        <test-method status="FAIL" signature="testMethod1()[pri:0, instance:testclasses.TestNG_ITestResultDemo@6ea12c19]" name="testMethod1" duration-ms="16" started-at="2018-04-26T16:22:55Z" finished-at="2018-04-26T16:22:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at testclasses.TestNG_ITestResultDemo.testMethod1(TestNG_ITestResultDemo.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testclasses.TestNG_ITestResultDemo@6ea12c19]" name="afterMethod" is-config="true" duration-ms="15" started-at="2018-04-26T16:22:55Z" finished-at="2018-04-26T16:22:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testMethod1 status=FAILURE method=TestNG_ITestResultDemo.testMethod1()[pri:0, instance:testclasses.TestNG_ITestResultDemo@6ea12c19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testclasses.TestNG_ITestResultDemo@6ea12c19]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-04-26T16:22:55Z" finished-at="2018-04-26T16:22:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testMethod2 status=SUCCESS method=TestNG_ITestResultDemo.testMethod2()[pri:0, instance:testclasses.TestNG_ITestResultDemo@6ea12c19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="testMethod2()[pri:0, instance:testclasses.TestNG_ITestResultDemo@6ea12c19]" name="testMethod2" duration-ms="0" started-at="2018-04-26T16:22:55Z" finished-at="2018-04-26T16:22:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
      </class> <!-- testclasses.TestNG_ITestResultDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
